### ISSUE TITLE
ansible-vault maintainer

### ISSUE THREAD

**Issue by timbroder** [kbrebanov/go-atlantic#1]
Hello,

I apologize for opening a ticket in another repository like this but I couldn't find another way to contact you.

I see you archived [Ansible-vault](https://github.com/kbrebanov/ansible-vault/). Would you be interested in me becoming it's maintainer and un-archiving it? I'm happy to do it as we use it in our setup

Thanks for your consideration

**Comment by kbrebanov** [comment]
Hi Tim,

Can't you just fork it and add your fork to Ansible Galaxy?

**Comment by timbroder** [comment]
I can I just thought it would be cleaner and better to have all the issue/PR history in one place.

If you prefer I just use a fork I'm good with that but could you also archive this? https://galaxy.ansible.com/kbrebanov/vault

**Comment by kbrebanov** [comment]
I can't see anywhere in Ansible Galaxy itself where a role can be archived...
